# Generated by Django 3.2.12 on 2022-05-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_studentrequest_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='User1',
            new_name='StudentUser',
        ),
    ]
