# Generated by Django 3.2.12 on 2022-05-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_user1_request_studentuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='StudentUser',
            new_name='StudentUser1',
        ),
    ]
