# Generated by Django 3.2.12 on 2022-05-04 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_rename_studentuser_request_studentuser1'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='VolunteerUser1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='VolunteerUser1', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='StudentUser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentUser1', to=settings.AUTH_USER_MODEL),
        ),
    ]
