# Generated by Django 3.2.12 on 2022-05-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220504_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablevolunteer',
            name='Volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
    ]
