# Generated by Django 3.2.12 on 2022-05-04 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_alter_availablevolunteer_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablevolunteer',
            name='User1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
